### ISSUE TITLE
using colon in one parameter causes a weird replacement by underscores

### ISSUE THREAD

**Issue by joananeves** [beanstalkd/beaneater#87]
I'm using ruby 2.6.6, and when changed from beaneater 1.1.1 to 1.1.2, got a json parse problem.

If I use colon in one of the parameters, I get this error (removing the colon will have success):
```
[2022-10-14 15:46:09] #00 ERROR: Exception Backburner::Job::JobFormatInvalid -> Job body could not be parsed: #<JSON::ParserError: 859: unexpected token at '{"action_list":["reconfigure_journals"],"app_digest":"","brand":"toconline","destination_tube":"accounting-ops-reconfigure","entity_id":"265843","entity_schema":"pt999999990_c265843","entity_variable_ids":"","fiscal_year_name":"Exercício de 2022","id":"3376","module_mask":"511","notification_title":"Redefinir configuração: Exercício de 2022","product"_"toconline","role_mask"_"32772","sharded_schema"_"pt999999990_c265843","source_company_id"_63571,"source_prefix"_"y2022_12_","source_schema"_"pt221170391_97586","source_user_id"_null,"subentity_id"_"pt999999990_16_1#y2022_1_","subentity_prefix"_"y2022_1_","subentity_schema"_"pt999999990_16_1","ttr"_21600,"tube"_"job_controller","user_email"_"rita.cunha+cluster1@cldware.com","user_id"_"750063","validity"_21600,"x_brand"_"toconline","x_product"_"toconline"}
'>
   /Users/joana/.rbenv/versions/2.6.6/lib/ruby/2.6.0/delegate.rb:85:in `call'
   /Users/joana/.rbenv/versions/2.6.6/lib/ruby/2.6.0/delegate.rb:85:in `method_missing'
   /Users/joana/.rbenv/versions/2.6.6/gemsets/toconline-rubies-jobs/gems/backburner-1.6.0/lib/backburner/job.rb:30:in `rescue in initialize'
   /Users/joana/.rbenv/versions/2.6.6/gemsets/toconline-rubies-jobs/gems/backburner-1.6.0/lib/backburner/job.rb:22:in `initialize'
   /Users/joana/.rbenv/versions/2.6.6/gemsets/toconline-rubies-jobs/gems/backburner-1.6.0/lib/backburner/worker.rb:178:in `new'
   /Users/joana/.rbenv/versions/2.6.6/gemsets/toconline-rubies-jobs/gems/backburner-1.6.0/lib/backburner/worker.rb:178:in `reserve_job'
   /Users/joana/work/sp-job/lib/sp/job/worker.rb:52:in `work_one_job'
   /Users/joana/work/sp-job/lib/sp/job/worker.rb:30:in `block in start'
   /Users/joana/work/sp-job/lib/sp/job/worker.rb:28:in `loop'
   /Users/joana/work/sp-job/lib/sp/job/worker.rb:28:in `start'
   /Users/joana/.rbenv/versions/2.6.6/gemsets/toconline-rubies-jobs/gems/backburner-1.6.0/lib/backburner/worker.rb:60:in `start'
   /Users/joana/.rbenv/versions/2.6.6/gemsets/toconline-rubies-jobs/gems/backburner-1.6.0/lib/backburner.rb:40:in `work'
   /Users/joana/work/toconline/jobs/toc-fast/toc-fast:47:in `<top (required)>'
```

With the following job submitted:

<img width="1181" alt="Screenshot 2022-10-14 at 16 44 23" src="https://user-images.githubusercontent.com/7079907/195890966-b95a70bc-f738-43fe-ae9a-0abf4d4a94f5.png">

**Comment by nesquena** [comment]
Thanks for the report. Stick to 1.1.1 for the time being. I'll take a look and push a fix when I can.

**Comment by joananeves** [comment]
Thanks @nesquena 
That's what I did locked to 1.1.1.

**Comment by nesquena** [comment]
1.1.2 has been yanked as well until we find a suitable fix

**Comment by pond** [comment]
We are reviewing #88 as a fix. Apologies again for the bug.

**Comment by nesquena** [comment]
I can confirm all tests were passing for me as well, and it seemed to work locally. Pushed 1.1.3 out live! Thanks for your help

**Comment by joananeves** [comment]
Hi @nesquena @pond 
I confirm that 1.1.3 is working for me.
Thanks to both!

**Comment by nesquena** [comment]
> Hi @nesquena @pond 
> 
> I confirm that 1.1.3 is working for me.
> 
> Thanks to both!

Great news, thanks for confirming!
